language: cpp

# whitelist
branches:
  only:
    - dev
    - master

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq gnuplot-x11

script:
    - gcc -o bioreactor bioreactor.cxx
    - ./bioreactor > bioreactor.dat
    - gnuplot bioreactor.plt
